### ISSUE TITLE
Provide Support For @reduxjs/toolkit

### ISSUE THREAD

**Issue by ctaylor4874** [welldone-software/why-did-you-render#95] opened 2020-03-12 21:16 UTC
There is an issue when trying to use `trackExtraHooks: [[ReactRedux, "useSelector"]]` when using [@reduxjs/toolkit](https://github.com/reduxjs/redux-toolkit#redux-toolkit). I was following the example [here](https://medium.com/welldone-software/why-did-you-render-v4-released-48e0f0b99d4c)

#### This error is thrown and the application cannot load.

![Screen Shot 2020-03-12 at 4 15 16 PM](https://user-images.githubusercontent.com/8881198/76567429-b72b1e00-647c-11ea-81b1-abc8b7437301.png)

**Comment by vzaidman** [comment] 2020-03-18 15:57
duplicate of #98 indeed

**Closed by vzaidman** 2020-03-18 15:57 UTC

**Comment by vzaidman** [comment] 2020-03-18 16:09
the issue is discussed at #85 with a workaround
