### ISSUE TITLE
[react-hook-form lib] Different objects that are equal by value for proxied hooks objects

### ISSUE THREAD

**Issue by ogabrielsantos** [welldone-software/why-did-you-render#159] opened 2020-11-15 00:12 UTC
**Describe the bug**
First I've [reported a issue here](https://github.com/react-hook-form/react-hook-form/issues/3451) but investigating, looks like WDYR says that objects are equal by value when they aren't.

**Codesandbox link**
https://codesandbox.io/s/react-hook-form-useform-template-forked-rdtej

**Steps to reproduce the behavior:**
- Open Codesandbox;
- Click on LastName input;
- DON'T Type anything;
- Leave field;
- See console log:

> - Firsts logs showing empty `errors` objects;
> - Then WDYR sayng "different objects that are equal by value.", when they aren't the same;
> - And last log shows the new, changed, error object

**Expected behavior**
WDYR should not log when props changed by reference and value

**Comment by vzaidman** [comment] 2020-11-15 11:29
Ok, the problem is with the library `react-hook-form` here:
https://github.com/react-hook-form/react-hook-form/blob/master/src/useForm.ts#L409

useState should not be mutated, but this library does it, by changing errors directly which is part of the state.

It's actually a great bug to open on them if it's not open because WDYR is far from being the only thing affected by this bug.

**Comment by vzaidman** [comment] 2020-11-15 11:37
know what? i'll open the bug

**Comment by vzaidman** [comment] 2020-11-16 09:08
sadly, this library does something non-standard, so i can't help with it.
I'll try to implement #114 asap so we can turn it off for the library though.

**Comment by vzaidman** [comment] 2020-11-16 09:08
will be fixed along with #114

**Closed by vzaidman** 2020-11-16 09:08 UTC
Labels: blocked by an issue in another library, bug, duplicate
