### ISSUE TITLE
class constructors must be invoked with |new|

### ISSUE THREAD

**Issue by screaney** [welldone-software/why-did-you-render#5] opened 2019-01-15 20:38 UTC
Trying to implement base functionality on our existing React app.

Getting 

> class constructors must be invoked with |new|

 for any component I add the static property to.

It looks like this is a common issue across this library and the predecessors, but I was under the impression this library had it solved, so I must be missing something.

I've attached the library via NPM as well as manually adding the src to see if I could narrow it down.  Best I can tell the error is thrown here (line 505):
`_this = _possibleConstructorReturn(this, _getPrototypeOf(WDYRPatchedClassComponent).call(this, props, context));`

Excluding markup, my component looks like this:
`class Home extends React.Component {

constructor(props) {
        super(props);
    }
static whyDidYouRender = true;
render(){
...
}
export default Home;
`

**Comment by vzaidman** [comment] 2019-01-16 21:30
this is what suppose to be there hmmmmm

**Comment by vzaidman** [comment] 2019-01-16 21:31
try
```
`class Home extends React.Component {

constructor(props) {
super(props);
}
render(){
...
}
Home.whyDidYouRender = true
export default Home;
```

**Comment by screaney** [comment] 2019-01-16 21:32
Same Result

**Comment by vzaidman** [comment] 2019-01-16 21:33
do you use
https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html
?

**Comment by screaney** [comment] 2019-01-16 21:34
Yes, our webpack is 

```
"plugins": [
                        "@babel/plugin-syntax-dynamic-import",
                        "@babel/plugin-syntax-import-meta",
                        ["@babel/plugin-proposal-class-properties", {
                            "loose": false
                        }],
                        "@babel/plugin-proposal-json-strings"
                    ]
```

**Comment by vzaidman** [comment] 2019-01-16 21:42
react 16.7.0?

**Comment by screaney** [comment] 2019-01-16 21:45
I could've sworn it was 16.7, but it looks like it's 16.6, updating now, will retest

**Comment by vzaidman** [comment] 2019-01-16 22:06
plesae try
```
import whyDidYouRender from '@welldone-software/why-did-you-render/dist/umd/whyDidYouRender';
```

**Comment by screaney** [comment] 2019-01-16 22:10
Updated to React 16.7, also changed to using that import.  No change, same error.

**Comment by vzaidman** [comment] 2019-01-16 22:18
it might be related to `babel-polyfill`. do you have a polyfill?

**Comment by vzaidman** [comment] 2019-01-16 22:20
also, by reading https://github.com/babel/babel/issues/7022
it might be the class being extended is transpiled differently then how it is extended in the library.

**Comment by vzaidman** [comment] 2019-01-16 22:30
ok, please try
`yarn add git+https://github.com/welldone-software/why-did-you-render.git#dont-transform-classes`
i think i identified the problem

**Comment by andrew1007** [comment] 2019-01-17 04:14
Fixed it for me :). Much thanks

**Comment by screaney** [comment] 2019-01-17 17:26
I pulled your branch as recommended and it now appears to be working.

**Comment by vzaidman** [comment] 2019-01-19 13:56
fixed in [v2.5.0](https://github.com/welldone-software/why-did-you-render/releases/tag/v2.5.0).

If you are not transpiling your classes, the library should be built without class transpilations as well.

So we added 3 endpoints where it is indeed not transpiled:
```
  "main-no-classes-transpile": "dist/no-classes-transpile/cjs/whyDidYouRender.min.js",
  "module-no-classes-transpile": "dist/no-classes-transpile/esm/whyDidYouRender.min.js",
  "browser-no-classes-transpile": "dist/no-classes-transpile/umd/whyDidYouRender.min.js",
```
to use it, import the library like this:
```
const whyDidYouRender = require('@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min.js');
```

**Comment by vzaidman** [comment] 2019-01-22 08:21
@screaney does it works for you?

also notice we can eliminate these endpoints once https://github.com/babel/babel/pull/8656 is merged.

**Comment by mschipperheyn** [comment] 2019-02-27 14:38
Finally was able to create a workaround. I'm extending an existing babel config that covers both client and server and I'm running into this on the node side of things. But the key is to exclude `babel-plugin-transform-classes` / `@babel/plugin-transform-classes`

```
const razzleBabel = require('razzle/babel');

module.exports = function babelConfig(api) {
	api.cache(true);

	const babel = razzleBabel();

	babel.presets[0] =
		process.env.BUILD_TARGET === 'client'
			? [
				require.resolve('@babel/preset-env'),
				{
					modules: false,
				},
			  ]
			: [
				require.resolve('@babel/preset-env'),
				{
					targets: {
						node: 'current',
					},
					exclude: [
						'babel-plugin-transform-classes',
						'@babel/plugin-transform-classes',
					],
					modules: false,
				},
			  ];
                  [..]
```

**Comment by vzaidman** [comment] 2019-02-27 15:13
again:
* The library extends all your (react class components) (not functional components by the way).
* Transpiled to es5 class cannot extend a native class currently until babel/babel#8656 is merged.
* If you transpile your classes, use:
```
const whyDidYouRender = require('@welldone-software/why-did-you-render);
```
* If you use native es6 classes, use:
```
const whyDidYouRender = require('@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min.js');
```
(or the equivalent import functions)

**Comment by frederikhors** [comment] 2019-04-26 14:57
Same error here using the `create-react-app` **3** and this import:

`const whyDidYouRender = require('@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min.js')`.

My browserlist:


```
  "browserslist": {
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

Maybe you should re-open this issue.

**Comment by maxportmc** [comment] 2019-07-18 09:55
Getting the same issue as @frederikhors using create-react-app. Is there any workaround?

**Comment by vzaidman** [comment] 2019-07-18 16:47
I don't see this bug in the sandbox:
https://codesandbox.io/s/youthful-nobel-7ebmd

try to reproduce it please.

**Comment by vzaidman** [comment] 2019-07-18 16:48
did you try
```
const whyDidYouRender = require("@welldone-software/why-did-you-render");
```
?

**Comment by vzaidman** [comment] 2019-07-18 16:50
I think i get it.
You are using `"last 1 safari version"` so you DO need to use the default version of the library:
```
const whyDidYouRender = require("@welldone-software/why-did-you-render");
```
The `no-classes-transpile` version is only if you build for latest browsers where the `class` keyword is supported natively.

**Comment by maxportmc** [comment] 2019-07-22 14:33
I have given it a go with the default version but no luck.I get the same error 

"TypeError: Class constructor Dashboard cannot be invoked without 'new'"

After some messing around I got it working in some components and realised it is failing in all the components with react-redux's connect import.

**Comment by vzaidman** [comment] 2019-07-22 15:03
are you using the last react-redux version?

**Comment by maxportmc** [comment] 2019-07-23 13:45
Was on version 5.1.0, just updated to 7.1.0 but same error using both versions of the library. I will see if I can recreate the error in a sandbox.

**Comment by vzaidman** [comment] 2019-09-09 17:15
I decided to close this issue since I understand very well why it happens and that it is solved already:
https://github.com/welldone-software/why-did-you-render/issues/5#issuecomment-467900253

If anybody has new information and / or able to reproduce it here:
https://codesandbox.io/s/welldone-softwarewhy-did-you-render-with-reactredux-fc8es

I'll obviously re-open it.

**Closed by vzaidman** 2019-09-09 17:15 UTC
Labels: bug
