### ISSUE TITLE
Next.js integration

### ISSUE THREAD

**Issue by mikestopcontinues** [welldone-software/why-did-you-render#84] opened 2020-01-29 20:50 UTC
I've tried a number of locations, and I can't seem to make this work with Next. What's the recommended solution? Thanks!

**Comment by vzaidman** [comment] 2020-01-30 06:47
I got to add it to the next.js examples indeed.

you can add it as an entry in `next.config.js`:

```
 webpack: (config, {dev, isServer, defaultLoaders}) => {
.....
    if (dev && !isServer) {
      const originalEntry = config.entry;
      config.entry = async () => {
        const entries = await originalEntry();
        if (entries['main.js'] && !entries['main.js'].includes('./common/whyDidYouRender.js')) {
          entries['main.js'].unshift('./common/whyDidYouRender.js');
        }
        return entries;
      };
    }
```
where `./common/whyDidYouRender.js` looks like this:
```
import React from 'react';
import whyDidYouRender from '@welldone-software/why-did-you-render';

whyDidYouRender(React);
```

**Comment by vzaidman** [comment] 2020-01-30 06:48
If anybody wants to open a `next.js` example here:
https://github.com/zeit/next.js/tree/master/examples

please notify me in this ticket.

**Comment by motiko** [comment] 2020-02-24 17:06
I've created a PR https://github.com/zeit/next.js/pull/10662

**Comment by vzaidman** [comment] 2020-02-24 17:14
> I've created a PR [zeit/next.js#10662](https://github.com/zeit/next.js/pull/10662)

beautiful!
when it's merged, you can open a PR with a link to the example added to the readme, so you would become a contributer of this library as well!
Thank you!

**Comment by motiko** [comment] 2020-02-28 10:23
Quick update, message from maintainers:

> This example is modifying the main entry using custom webpack configuration, let's try to avoid these kind of changes as they may cause unexpected issues, like hydration errors.
> 
> Please use a different method or give more information about why does it have to be this way 🙏

You can see [my answer here](https://github.com/zeit/next.js/pull/10662#issuecomment-591819120) . Hope it is enough and feel free to jump into the conversation if you feel like it @vzaidman  😃

**Comment by motiko** [comment] 2020-03-06 09:58
Created a [PR](https://github.com/motiko/why-did-you-render/pull/1)

**Comment by vzaidman** [comment] 2020-03-06 10:07
here is a [working example of integration with next.js](https://github.com/zeit/next.js/tree/canary/examples/with-why-did-you-render).
If for some reason the proposed way doesn't work, you can always try using the [more intrusive but reliable way I proposed at the comment above](https://github.com/welldone-software/why-did-you-render/issues/84#issuecomment-580107735).

**Closed by vzaidman** 2020-03-06 10:07 UTC
Labels: good first issue, help wanted

**Comment by mikestopcontinues** [comment] 2020-05-05 18:07
With one of the recent Next updates, neither one of these methods work. 

@vzaidman `config.entry` is now a function. Wrapping and resolving the function, then prepending the whyDidYouRender script completely breaks Next. 

And @motiko, I'm sorry to say your solution simply doesn't result in any output. 

Do either of you have any other ideas?

**Comment by francescovenica** [comment] 2020-05-20 10:42
are these solutions working on the last versions of wdyr and next? I can't get it working...no errore but nothing in console

**Comment by mikestopcontinues** [comment] 2020-05-20 11:44
@francescovenica I still haven't figured it out, and I gave it a good go.

**Comment by Vadorequest** [comment] 2020-05-26 10:55
I'll give it a try. I just stumbled upon WDYU and I think that'd be a great addition to https://github.com/UnlyEd/next-right-now

Maybe I'll add into https://github.com/UnlyEd/next-right-now/pull/42 if I get it to work.

**Comment by Vadorequest** [comment] 2020-05-26 11:08
I've tried to add the following in `_app`, and while it doesn't seem to create any issue, it doesn't seem to do anything either. I've never used WDYU before so I'm not quite sure what to expect to be printed on the console. Could someone else confirm it does/not work?

```js
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  // eslint-disable-next-line no-console
  console.debug('Applying whyDidYouRender');
  whyDidYouRender(React);
}
```

**Comment by vzaidman** [comment] 2020-05-26 15:29
try
```
if (process.env.NODE_ENV === 'development') {
  if (typeof window !== 'undefined') {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React, {
      trackAllPureComponents: true
    });
  }
}
```

**Comment by Vadorequest** [comment] 2020-05-26 15:46
Much better, thanks!

Getting this now:

![image](https://user-images.githubusercontent.com/3807458/82921338-90a75a00-9f78-11ea-9324-83c69361193e.png)

So, it seems there are a few useless re-renders (2, at least), but I don't see how those information can help me knowing from what components they came from.

I tried, but can't locate the component that re-renders unnecessarily. Is that the expected behaviour?

**Comment by Vadorequest** [comment] 2020-05-26 15:55
Alright, I also get this and understand a bit more how the logging is meant to work.

![image](https://user-images.githubusercontent.com/3807458/82922501-f6481600-9f79-11ea-84e6-5215c414f836.png)

Basically, it seems to be working fine to me, it's just that the `ReactAsyncHighlighter` wasn't a component I had expected (it's not one of mine, so the name didn't trigger any bell, unlike `Code` and `CodeBlock`)

So, looks like https://github.com/welldone-software/why-did-you-render/issues/84#issuecomment-634098621 does the job for Next.js. :)

**Comment by vzaidman** [comment] 2020-05-26 16:51
sadly it seems like issue https://github.com/welldone-software/why-did-you-render/issues/114 that i didn't solve yet.

look inside for a workaround (in short it is assigning `ReactAsyncHighlighter.whyDidYouRender = false`)

**Comment by Vadorequest** [comment] 2020-05-26 19:21
Thanks for the link, I understand the underlying issue, it's unrelated to Next.js.

@francescovenica @mikestopcontinues https://github.com/welldone-software/why-did-you-render/issues/84#issuecomment-634098621 should do the trick for your Next.js app. I have it working using Next 9.4.0.

My commit:
[https://github.com/UnlyEd/next-right-now/pull/52/commits/b54f416c6626a8de7bba0087e6203d55286be9d8 ](https://github.com/UnlyEd/next-right-now/pull/52/commits/b54f416c6626a8de7bba0087e6203d55286be9d8)

**Comment by nandorojo** [comment] 2021-01-20 22:04
Just checking in here, does this work if I do it in a Next.js app?

```js
if (process.env.NODE_ENV === 'development') {
  if (typeof window !== 'undefined') {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React, {
      trackAllPureComponents: true
    });
  }
}
```

**Comment by Vadorequest** [comment] 2021-01-20 23:46
@nandorojo Here's what I did:
https://github.com/UnlyEd/next-right-now/blob/0174dcc21e36dd356e2be475bfca5339baf27fd3/src/modules/core/wdyr/wdyr.tsx

Imported from `_app`: https://github.com/UnlyEd/next-right-now/blob/0174dcc21e36dd356e2be475bfca5339baf27fd3/src/pages/_app.tsx#L10

And with a custom CSS style too:
https://github.com/UnlyEd/next-right-now/blob/0174dcc21e36dd356e2be475bfca5339baf27fd3/src/layouts/core/components/Head.tsx#L110-L117

**Comment by ivadenis** [comment] 2022-02-10 22:03
Tried different approaches but wasnt able to make it work with next 12. No console output.

**Comment by dwilt** [comment] 2022-02-14 00:46
@ivadenis did you try wiping the `.next` build folder and then re-running the dev server (`next dev`)?

```shell
rm -rf .next; next dev
```

For me, in our next project, I've noticed that WDYR doesn't enable unless you wipe the build folder

**Comment by ktravelet** [comment] 2022-02-23 00:46
hey all, having issues here too.  At the top of of wdyr.tsx I put the following logger, and `typeof window` is always undefined. 

```
console.log(
  `testing if WDYR.  (typeof window): ${
    typeof window
  }. process.env.NODE_ENV: ${process.env.NODE_ENV}`
);
```

**Comment by hems** [comment] 2022-08-28 01:02
> Tried different approaches but wasnt able to make it work with next 12. No console output.

any updates on this?

**Comment by apperside** [comment] 2022-12-12 15:51
There was no way to make it work for me: I added webpack config as suggested by @vzaidman , I ensured that it was loading wdyr.ts file by adding a log, I tried serveral babel tricks, but nothing worked untill I added the following

`"jsxImportSource": "@welldone-software/why-did-you-render"`

to `tsconfig.ts`

From that moment onward, it started finally working!

**Comment by hems** [comment] 2022-12-15 11:01
Is there an "official solutioon" ?

I would expect this issue to be closed only when a solution was added to the README?

**Comment by rocketana** [comment] 2022-12-25 04:55
I tried all solutions from this thread, none of them works with Next,js 13. 

Importing `whyDidYouRender.js` script in the root layout did nothing (well, it shouldn't, as it's a server component). 

Adding it to the next.config webpack did nothing. I tested that it's added by printing webpack entries to the console, the absolute file path was there. Logging from the file never happened. 

Importing it in a top level client component did also nothing. And logging from the script was printed to both, the browser console and the server terminal, it looks like it runs on the server being imported in a client component? (Sounds like I don't understand something, I'm still learning the concepts of Next.js 13 and client/server components). Anyway, it didn't work this way.

I then tried to init `whyDidYouRender` directly in a top level client component. It then starts to break the app with an error `React has detected a change in the order of Hooks` caused by `HotReload` and `Router`.

```
   Previous render            Next render
   ------------------------------------------------------
1. useMemo                    useMemo
2. useRef                     useRef
3. useRef                     useRef
4. useEffect                  useEffect
5. useReducer                 useReducer
6. useCallback                useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The problem with hooks order's disappeared sometimes for an unknown reason. A few times I was able to see the reasons for re-render after navigating successfully. But 99/100 times I just get the error about hooks order. With the same code and same actions (I just open a page and try to navigate using next.js links). 

It works fine until you try to navigate. I tested adding the following code to the top level client component and a child component. I got the reason as expected for both of them. I passed no options on the init. 

```
    const [objState, setObjState] = useState({ name: 'World' })

    useEffect(() => {
        setObjState({ name: 'World' })
    }, [])
```

**Comment by hems** [comment] 2023-01-23 18:42
> I tried all solutions from this thread, none of them works with Next,js 13.

Unfortunately i didn't have time to test it with the new `app` folder yet, but i created a new issue ( since this one is closed ) asking for help with the new app folder.

You can [see the new issue here](https://github.com/welldone-software/why-did-you-render/issues/266)

I also pointed to an example from the official documentation that hopefully will be helpful in your situation.

**Comment by AlbinoGeek** [comment] 2023-08-19 23:47
I can't get this working in NextJS 13 either, even in `pages/` as normal.

Also tried everything in this thread, including the `jsxImportSource`.

Simply put, the import does literally nothing, no changes to output.

**Comment by Xamsix** [comment] 2024-02-16 16:13
For anyone still experiencing issues, I'm on **Next 14**. Got it to to work by doing;

1. Create a component , in my case, `wdyr.tsx`. Make sure it renders on the client.

```
"use client";
import React from "react";

if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  const whyDidYouRender = require("@welldone-software/why-did-you-render");

  console.debug(
    "Applying whyDidYouRender, to help you locate unnecessary re-renders during development. See https://github.com/welldone-software/why-did-you-render"
  );

  whyDidYouRender(React, {
    trackAllPureComponents: true,
    trackHooks: true,
    logOwnerReasons: true,
    collapseGroups: true,
  });
}
```

Then in my app directory, I have a `layout.tsx` that is applied to all the pages. In there, I import the component like;
`import "@/components/wdyr";`

Make sure you adjust it to your location and way of importing.

**Comment by YoannBuzenet** [comment] 2024-07-15 15:50
Can't make it work neither. Did anyone find something?

**Comment by prateek041** [comment] 2025-04-12 06:33
Anything outside Next doesn't work with Next ?

**Comment by stekovinbranturry** [comment] 2025-05-15 02:34
after done a lot of trying, finally it works in my next 13 + react 18 project. Here is my resolution:

1. check your react version, make sure install a correct wdyr version, like react 18 -> wdyr@8
2. make wdyr to be a wrapper, instead of just import it in entry file
- src/components/wdyr.tsx
```tsx
import React from 'react';

if (process.env.NODE_ENV === 'development') {
  if (typeof window !== 'undefined') {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const whyDidYouRender = require('@welldone-software/why-did-you-render');

    whyDidYouRender(React, {
      trackAllPureComponents: true,
      trackHooks: true,
      logOnDifferentValues: true,
      hotReload: true,
    });
  }
}
```
- src/components/WDYRWrapper.tsx
```tsx
'use client';

import React from 'react';
import './wdyr';

function WDYRWrapper({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export default WDYRWrapper;
```
- app/layout.tsx
```tsx
import WDYRWrapper from '@/components/WDYRWrapper';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <WDYRWrapper>{children}</WDYRWrapper>
      </body>
    </html>
  );
}
```

3. You can test a component by adding `Component.whyDidYouRender = true;`

![Image](https://github.com/user-attachments/assets/611606a5-d44e-4d09-b685-0a19370e0090)

**Comment by stekovinbranturry** [comment] 2025-05-15 02:35
> Can't make it work neither. Did anyone find something?

you can try my resolution:

https://github.com/welldone-software/why-did-you-render/issues/84#issuecomment-2882039746

**Comment by qiujie8092916** [comment] 2025-07-01 07:16
works for me (next 14(App Router) + react 18):
```ts
// next.config.js
webpack: (config, { dev, isServer }) => {
  if (dev && !isServer) {
      const originalEntry = config.entry;
      config.entry = async () => {
        const entries = await originalEntry();
        if (entries['main-app'] && !entries['main-app'].includes('./why-did-you-render.js')) {
          entries['main-app'].unshift('./why-did-you-render.js');
        }
        return entries;
      };
    }

    return config;
  },
```
```ts
// why-did-you-render.js
import React from "react";
import whyDidYouRender from "@welldone-software/why-did-you-render";

whyDidYouRender(React);

```
